name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask






https://mybinder.org/v2/gh/saloneedesaee/saloneedesaee.github.io/HEAD?urlpath=https%3A%2F%2Fgithub.com%2Fsaloneedesaee%2Fsaloneedesaee.github.io%2Fblob%2Fmain%2FDemo1.ipynb